// export const users = {
//   name: 'Caroline Victor-Pujebet',
//   email: 'caroline_pujebet@hotmail.com',
//   profile_picture: 'T0WU5R8NT-U01C4AC9BUY-93e74dc2edb4-512.jpg',
// };
// let users = {
//   name: 'Caroline Victor-Pujebet',
//   email: email,
//   profile_picture: 'T0WU5R8NT-U01C4AC9BUY-93e74dc2edb4-512.jpg',
//   movies: {
//     last_seen: 773655,
//     want_to_see: [749618, 441282],
//     liked: [508442, 615677, 524047, 773655],
//     disliked: [577922, 553604],
//     favourites: [464052, 19190],
//   },
// };

export const users = [
  {
    id: 1,
    user_name: 'Caroline Victor-Pujebet',
    profile_picture: 'T0WU5R8NT-U01C4AC9BUY-93e74dc2edb4-512.jpg',
    user_movies: {
      last_seen: 773655,
      want_to_see: [749618, 441282],
      liked: [508442, 615677, 524047, 773655],
      disliked: [577922, 553604],
      favourites: [464052, 19190],
    },
    nb_seen: 8,
  },
];

// export const movies = [
//   {
//     adult: false,
//     backdrop_path: '/srYya1ZlI97Au4jUYAktDe3avyA.jpg',
//     genre_ids: [14, 28, 12],
//     id: 464052,
//     original_language: 'en',
//     original_title: 'Wonder Woman 1984',
//     overview:
//       'Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.',
//     popularity: 6017.605,
//     poster_path: '/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
//     release_date: '2020-12-16',
//     title: 'Wonder Woman 1984',
//     video: false,
//     vote_average: 7.3,
//     vote_count: 2153,
//   },
//   {
//     adult: false,
//     backdrop_path: '/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg',
//     genre_ids: [16, 35, 18, 10402, 14],
//     id: 508442,
//     original_language: 'en',
//     original_title: 'Soul',
//     overview:
//       'Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.',
//     popularity: 4025.905,
//     poster_path: '/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
//     release_date: '2020-12-25',
//     title: 'Soul',
//     video: false,
//     vote_average: 8.5,
//     vote_count: 2714,
//   },
//   {
//     adult: false,
//     backdrop_path: '/dueiWzWc81UAgnbDAyH4Gjqnh4n.jpg',
//     genre_ids: [18, 878],
//     id: 614911,
//     original_language: 'en',
//     original_title: 'The Midnight Sky',
//     overview:
//       'A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.',
//     popularity: 3402.617,
//     poster_path: '/51JxCk77ZCqLzbLkrDl9Qho6KUh.jpg',
//     release_date: '2020-12-10',
//     title: 'The Midnight Sky',
//     video: false,
//     vote_average: 6,
//     vote_count: 748,
//   },
//   {
//     adult: false,
//     backdrop_path: '/ibwOX4xUndc6E90MYfglghWvO5Z.jpg',
//     genre_ids: [878, 12],
//     id: 517096,
//     original_language: 'ru',
//     original_title: 'Вратарь Галактики',
//     overview:
//       'Cosmoball is a mesmerizing intergalactic game of future played between humans and aliens at the giant extraterrestrial ship hovering in the sky over Earth. A young man with enormous power of an unknown nature joins the team of hot-headed superheroes in exchange for a cure for his mother’s deadly illness. The Four from Earth will fight not only to defend the honor of their home planet in the spectacular game, but to face the unprecedented threat to the Galaxy and embrace their own destiny.',
//     popularity: 3631.275,
//     poster_path: '/eDJYDXRoWoUzxjd52gtz5ODTSU1.jpg',
//     release_date: '2020-08-27',
//     title: 'Cosmoball',
//     video: false,
//     vote_average: 4.7,
//     vote_count: 25,
//   },
//   {
//     adult: false,
//     backdrop_path: '/yR27bZPIkNhpGEIP3jKV2EifTgo.jpg',
//     genre_ids: [16, 10751],
//     id: 755812,
//     original_language: 'fr',
//     original_title: 'Miraculous World: New York, United HeroeZ',
//     overview:
//       'During a school field trip, Ladybug and Cat Noir meet the American superheroes, whom they have to save from an akumatised super-villain. They discover that Miraculous exist in the United States too.',
//     popularity: 3373.033,
//     poster_path: '/kIHgjAkuzvKBnmdstpBOo4AfZah.jpg',
//     release_date: '2020-10-10',
//     title: 'Miraculous World: New York, United HeroeZ',
//     video: false,
//     vote_average: 8.6,
//     vote_count: 214,
//   },
//   {
//     adult: false,
//     backdrop_path: '/cjaOSjsjV6cl3uXdJqimktT880L.jpg',
//     genre_ids: [12, 14, 10751, 16],
//     id: 529203,
//     original_language: 'en',
//     original_title: 'The Croods: A New Age',
//     overview:
//       "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
//     popularity: 1586.556,
//     poster_path: '/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg',
//     release_date: '2020-11-25',
//     title: 'The Croods: A New Age',
//     video: false,
//     vote_average: 7.8,
//     vote_count: 954,
//   },
//   {
//     adult: false,
//     backdrop_path: '/z15NpieRw7jL7bKoICwLO5j7FgZ.jpg',
//     genre_ids: [878],
//     id: 733317,
//     original_language: 'en',
//     original_title: 'Monsters of Man',
//     overview:
//       "A robotics company vying to win a lucrative military contract team up with a corrupt CIA agent to conduct an illegal live field test. They deploy four weaponized prototype robots into a suspected drug manufacturing camp in the Golden Triangle, assuming they'd be killing drug runners that no one would miss. Six doctors on a humanitarian mission witness the brutal slaughter and become prime targets.",
//     popularity: 2292.579,
//     poster_path: '/1f3qspv64L5FXrRy0MF8X92ieuw.jpg',
//     release_date: '2020-11-19',
//     title: 'Monsters of Man',
//     video: false,
//     vote_average: 7.2,
//     vote_count: 110,
//   },
//   {
//     adult: false,
//     backdrop_path: '/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg',
//     genre_ids: [28, 53, 80, 18],
//     id: 553604,
//     original_language: 'en',
//     original_title: 'Honest Thief',
//     overview:
//       "A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.",
//     popularity: 2088.646,
//     poster_path: '/zeD4PabP6099gpE0STWJrJrCBCs.jpg',
//     release_date: '2020-09-03',
//     title: 'Honest Thief',
//     video: false,
//     vote_average: 6.8,
//     vote_count: 383,
//   },
//   {
//     adult: false,
//     backdrop_path: '/wk58aoyWpMTVkKkdjw889XfWGdL.jpg',
//     genre_ids: [53, 80, 9648],
//     id: 646593,
//     original_language: 'en',
//     original_title: 'Wander',
//     overview:
//       "After getting hired to probe a suspicious death in the small town of Wander, a mentally unstable private investigator becomes convinced the case is linked to the same 'conspiracy cover up' that caused the death of his daughter.",
//     popularity: 2253.909,
//     poster_path: '/2AwPvNHphpZBJDqjZKVuMAbvS0v.jpg',
//     release_date: '2020-12-04',
//     title: 'Wander',
//     video: false,
//     vote_average: 5.3,
//     vote_count: 61,
//   },
//   {
//     adult: false,
//     backdrop_path: '/wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
//     genre_ids: [28, 53, 878],
//     id: 577922,
//     original_language: 'en',
//     original_title: 'Tenet',
//     overview:
//       'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
//     popularity: 2009.491,
//     poster_path: '/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
//     release_date: '2020-08-22',
//     title: 'Tenet',
//     video: false,
//     vote_average: 7.4,
//     vote_count: 3645,
//   },
//   {
//     adult: false,
//     backdrop_path: '/UgNke0mMQhQdnX2hEu4cN83M0a.jpg',
//     genre_ids: [28, 14, 10751],
//     id: 615677,
//     original_language: 'en',
//     original_title: 'We Can Be Heroes',
//     overview:
//       "When alien invaders capture Earth's superheroes, their kids must learn to work together to save their parents - and the planet.",
//     popularity: 2473.191,
//     poster_path: '/1S21HpcKY6uQ9UAw68aICmrJaq6.jpg',
//     release_date: '2020-12-25',
//     title: 'We Can Be Heroes',
//     video: false,
//     vote_average: 6.1,
//     vote_count: 163,
//   },
//   {
//     adult: false,
//     backdrop_path: '/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg',
//     genre_ids: [28, 53],
//     id: 524047,
//     original_language: 'en',
//     original_title: 'Greenland',
//     overview:
//       "John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
//     popularity: 1139.453,
//     poster_path: '/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg',
//     release_date: '2020-07-29',
//     title: 'Greenland',
//     video: false,
//     vote_average: 7.1,
//     vote_count: 1232,
//   },
//   {
//     adult: false,
//     backdrop_path: '/jeAQdDX9nguP6YOX6QSWKDPkbBo.jpg',
//     genre_ids: [28, 14, 878],
//     id: 590706,
//     original_language: 'en',
//     original_title: 'Jiu Jitsu',
//     overview:
//       'Every six years, an ancient order of jiu-jitsu fighters joins forces to battle a vicious race of alien invaders. But when a celebrated war hero goes down in defeat, the fate of the planet and mankind hangs in the balance.',
//     popularity: 1111.565,
//     poster_path: '/eLT8Cu357VOwBVTitkmlDEg32Fs.jpg',
//     release_date: '2020-11-20',
//     title: 'Jiu Jitsu',
//     video: false,
//     vote_average: 5.4,
//     vote_count: 227,
//   },
//   {
//     adult: false,
//     backdrop_path: '/ckfwfLkl0CkafTasoRw5FILhZAS.jpg',
//     genre_ids: [28, 35, 14],
//     id: 602211,
//     original_language: 'en',
//     original_title: 'Fatman',
//     overview:
//       'A rowdy, unorthodox Santa Claus is fighting to save his declining business. Meanwhile, Billy, a neglected and precocious 12 year old, hires a hit man to kill Santa after receiving a lump of coal in his stocking.',
//     popularity: 1199.428,
//     poster_path: '/4n8QNNdk4BOX9Dslfbz5Dy6j1HK.jpg',
//     release_date: '2020-11-13',
//     title: 'Fatman',
//     video: false,
//     vote_average: 5.6,
//     vote_count: 299,
//   },
//   {
//     adult: false,
//     backdrop_path: '/lrzAb9QCwKPOwH1iY7WpfjR6jcC.jpg',
//     genre_ids: [10770, 53],
//     id: 648371,
//     original_language: 'en',
//     original_title: 'No Good Deed',
//     overview:
//       "Karen never planned on being a hero. A recent widow, she has her hands full with work and parenting her son Max. Then Karen saves Jeremy's life during a drug store robbery and quickly discovers that the young man is intent on paying her back at any cost. At first, life starts improving for this good Samaritan, but as Jeremy's efforts become more extreme, Karen starts to wonder if no good deed truly goes unpunished.",
//     popularity: 1320.007,
//     poster_path: '/27BnREBR5rcMrUVUhV5bTXlcCym.jpg',
//     release_date: '2020-03-13',
//     title: 'No Good Deed',
//     video: false,
//     vote_average: 6.7,
//     vote_count: 22,
//   },
//   {
//     adult: false,
//     backdrop_path: '/azTsf28VYj0rw6ql67fB8WnxbZX.jpg',
//     genre_ids: [53, 27],
//     id: 554585,
//     original_language: 'es',
//     original_title: 'Sin origen',
//     overview: 'A group of arcanes enjoy fighting vampires.',
//     popularity: 1180.268,
//     poster_path: '/77lI0btz8qkExY13MKXaPrf4cA6.jpg',
//     release_date: '2020-10-25',
//     title: 'Originless',
//     video: false,
//     vote_average: 5.6,
//     vote_count: 33,
//   },
//   {
//     adult: false,
//     backdrop_path: '/8knaRrDd1FM1pbSLaViEQSxodi5.jpg',
//     genre_ids: [18, 53],
//     id: 441282,
//     original_language: 'en',
//     original_title: 'Night Hunter',
//     overview:
//       'A Minnesota police officer crosses paths with a committed and tireless vigilante as he follows the trail of a ruthless predator responsible for several abductions and murders.',
//     popularity: 690.679,
//     poster_path: '/vVYU0x9FRpiJNX7c54ciFnRBVYG.jpg',
//     release_date: '2019-08-29',
//     title: 'Night Hunter',
//     video: false,
//     vote_average: 6.5,
//     vote_count: 415,
//   },
//   {
//     adult: false,
//     backdrop_path: '/fX8e94MEWSuTJExndVYxKsmA4Hw.jpg',
//     genre_ids: [28, 12, 80],
//     id: 604822,
//     original_language: 'zh',
//     original_title: '急先锋',
//     overview:
//       "Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.",
//     popularity: 1277.331,
//     poster_path: '/vYvppZMvXYheYTWVd8Rnn9nsmNp.jpg',
//     release_date: '2020-09-30',
//     title: 'Vanguard',
//     video: false,
//     vote_average: 7.3,
//     vote_count: 110,
//   },
//   {
//     adult: false,
//     backdrop_path: '/h3dqQ1uqHsNwIVDufe9AzI7KgVS.jpg',
//     genre_ids: [16, 10751],
//     id: 749618,
//     original_language: 'es',
//     original_title: 'El Camino de Xico',
//     overview:
//       'The peace of a small town is endangered when a corporation wants to destroy the mountain that protects them. A girl named Copi and her best friend Xico, a Xoloitzcuintle dog, will go into the mountains to try to save the town.',
//     popularity: 847.803,
//     poster_path: '/ssk0Gd27ziryP2OUxprIVhAvr3e.jpg',
//     release_date: '2020-11-12',
//     title: "Xico's Path",
//     video: false,
//     vote_average: 7.2,
//     vote_count: 28,
//   },
//   {
//     adult: false,
//     backdrop_path: '/xxEec408VQY7TIvtpxdkUM3Fux6.jpg',
//     genre_ids: [35],
//     id: 773655,
//     original_language: 'en',
//     original_title: 'Death to 2020',
//     overview:
//       "2020: A year so [insert adjective of choice here], even the creators of Black Mirror couldn't make it up… but that doesn't mean they don't have a little something to add. This comedy event that tells the story of the dreadful year that was — and perhaps still is? The documentary-style special weaves together some of the world's most (fictitious) renowned voices with real-life archival footage.",
//     popularity: 910.183,
//     poster_path: '/cXYmzvnBNhGPrkH3CWr58sHeZKh.jpg',
//     release_date: '2020-12-27',
//     title: 'Death to 2020',
//     video: false,
//     vote_average: 6.8,
//     vote_count: 199,
//   },
// ];
// export const users = [
//   {
//     id: 1,
//     user_name: 'Caroline Victor-Pujebet',
//     profile_picture: 'T0WU5R8NT-U01C4AC9BUY-93e74dc2edb4-512.jpg',
//     user_movies: {
//       last_seen: {
//         adult: false,
//         backdrop_path: '/xxEec408VQY7TIvtpxdkUM3Fux6.jpg',
//         genre_ids: [35],
//         id: 773655,
//         original_language: 'en',
//         original_title: 'Death to 2020',
//         overview:
//           "2020: A year so [insert adjective of choice here], even the creators of Black Mirror couldn't make it up… but that doesn't mean they don't have a little something to add. This comedy event that tells the story of the dreadful year that was — and perhaps still is? The documentary-style special weaves together some of the world's most (fictitious) renowned voices with real-life archival footage.",
//         popularity: 910.183,
//         poster_path: '/cXYmzvnBNhGPrkH3CWr58sHeZKh.jpg',
//         release_date: '2020-12-27',
//         title: 'Death to 2020',
//         video: false,
//         vote_average: 6.8,
//         vote_count: 199,
//       },
//       want_to_see: [
//         {
//           adult: false,
//           backdrop_path: '/h3dqQ1uqHsNwIVDufe9AzI7KgVS.jpg',
//           genre_ids: [16, 10751],
//           id: 749618,
//           original_language: 'es',
//           original_title: 'El Camino de Xico',
//           overview:
//             'The peace of a small town is endangered when a corporation wants to destroy the mountain that protects them. A girl named Copi and her best friend Xico, a Xoloitzcuintle dog, will go into the mountains to try to save the town.',
//           popularity: 847.803,
//           poster_path: '/ssk0Gd27ziryP2OUxprIVhAvr3e.jpg',
//           release_date: '2020-11-12',
//           title: "Xico's Path",
//           video: false,
//           vote_average: 7.2,
//           vote_count: 28,
//         },
//         {
//           adult: false,
//           backdrop_path: '/xxEec408VQY7TIvtpxdkUM3Fux6.jpg',
//           genre_ids: [35],
//           id: 773655,
//           original_language: 'en',
//           original_title: 'Death to 2020',
//           overview:
//             "2020: A year so [insert adjective of choice here], even the creators of Black Mirror couldn't make it up… but that doesn't mean they don't have a little something to add. This comedy event that tells the story of the dreadful year that was — and perhaps still is? The documentary-style special weaves together some of the world's most (fictitious) renowned voices with real-life archival footage.",
//           popularity: 910.183,
//           poster_path: '/cXYmzvnBNhGPrkH3CWr58sHeZKh.jpg',
//           release_date: '2020-12-27',
//           title: 'Death to 2020',
//           video: false,
//           vote_average: 6.8,
//           vote_count: 199,
//         },
//       ],
//       liked: [
//         {
//           adult: false,
//           backdrop_path: '/UgNke0mMQhQdnX2hEu4cN83M0a.jpg',
//           genre_ids: [28, 14, 10751],
//           id: 615677,
//           original_language: 'en',
//           original_title: 'We Can Be Heroes',
//           overview:
//             "When alien invaders capture Earth's superheroes, their kids must learn to work together to save their parents - and the planet.",
//           popularity: 2473.191,
//           poster_path: '/1S21HpcKY6uQ9UAw68aICmrJaq6.jpg',
//           release_date: '2020-12-25',
//           title: 'We Can Be Heroes',
//           video: false,
//           vote_average: 6.1,
//           vote_count: 163,
//         },
//         {
//           adult: false,
//           backdrop_path: '/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg',
//           genre_ids: [28, 53],
//           id: 524047,
//           original_language: 'en',
//           original_title: 'Greenland',
//           overview:
//             "John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
//           popularity: 1139.453,
//           poster_path: '/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg',
//           release_date: '2020-07-29',
//           title: 'Greenland',
//           video: false,
//           vote_average: 7.1,
//           vote_count: 1232,
//         },
//       ],
//     },
//     nb_seen: 8,
//   },
// ];

// export const db = {
//   page: 1,
//   results: [
//     {
//       backdrop_path: '/srYya1ZlI97Au4jUYAktDe3avyA.jpg',
//       id: 464052,
//       genre_ids: [14, 28, 12],
//       original_language: 'en',
//       original_title: 'Wonder Woman 1984',
//       poster_path: '/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
//       video: false,
//       vote_average: 7.3,
//       overview:
//         'Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.',
//       release_date: '2020-12-16',
//       vote_count: 2153,
//       title: 'Wonder Woman 1984',
//       adult: false,
//       popularity: 6017.605,
//       media_type: 'movie',
//     },
//     {
//       genre_ids: [16, 35, 18, 10402, 14],
//       original_language: 'en',
//       original_title: 'Soul',
//       poster_path: '/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
//       title: 'Soul',
//       id: 508442,
//       overview:
//         'Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.',
//       release_date: '2020-12-25',
//       vote_count: 2714,
//       vote_average: 8.5,
//       adult: false,
//       backdrop_path: '/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg',
//       video: false,
//       popularity: 4025.905,
//       media_type: 'movie',
//     },
//     {
//       overview:
//         'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
//       release_date: '2020-08-22',
//       adult: false,
//       backdrop_path: '/wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
//       genre_ids: [28, 53, 878],
//       vote_count: 3645,
//       original_language: 'en',
//       original_title: 'Tenet',
//       poster_path: '/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
//       video: false,
//       id: 577922,
//       vote_average: 7.4,
//       title: 'Tenet',
//       popularity: 2009.491,
//       media_type: 'movie',
//     },
//     {
//       vote_average: 6.0,
//       id: 614911,
//       overview:
//         'A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.',
//       release_date: '2020-12-10',
//       adult: false,
//       backdrop_path: '/dueiWzWc81UAgnbDAyH4Gjqnh4n.jpg',
//       genre_ids: [18, 878],
//       vote_count: 748,
//       original_language: 'en',
//       original_title: 'The Midnight Sky',
//       poster_path: '/51JxCk77ZCqLzbLkrDl9Qho6KUh.jpg',
//       title: 'The Midnight Sky',
//       video: false,
//       popularity: 3402.617,
//       media_type: 'movie',
//     },
//     {
//       video: false,
//       vote_average: 7.8,
//       overview:
//         "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
//       release_date: '2020-11-25',
//       adult: false,
//       backdrop_path: '/cjaOSjsjV6cl3uXdJqimktT880L.jpg',
//       vote_count: 954,
//       genre_ids: [12, 14, 10751, 16],
//       id: 529203,
//       original_language: 'en',
//       original_title: 'The Croods: A New Age',
//       poster_path: '/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg',
//       title: 'The Croods: A New Age',
//       popularity: 1586.556,
//       media_type: 'movie',
//     },
//     {
//       vote_average: 6.0,
//       title: 'Shadow in the Cloud',
//       overview:
//         'A WWII pilot traveling with top secret documents on a B-17 Flying Fortress encounters an evil presence on board the flight.',
//       release_date: '2020-12-31',
//       adult: false,
//       backdrop_path: '/aHYUj0hICtWZ5tPiCIm6pWUcjYK.jpg',
//       genre_ids: [28, 18, 27, 10752],
//       vote_count: 42,
//       original_language: 'en',
//       original_title: 'Shadow in the Cloud',
//       poster_path: '/t7EUMSlfUN3jUSZUJOLURAzJzZs.jpg',
//       id: 675327,
//       video: false,
//       popularity: 130.439,
//       media_type: 'movie',
//     },
//     {
//       adult: false,
//       backdrop_path: '/UgNke0mMQhQdnX2hEu4cN83M0a.jpg',
//       genre_ids: [28, 14, 10751],
//       original_language: 'en',
//       original_title: 'We Can Be Heroes',
//       poster_path: '/1S21HpcKY6uQ9UAw68aICmrJaq6.jpg',
//       video: false,
//       vote_average: 6.1,
//       vote_count: 163,
//       overview:
//         "When alien invaders capture Earth's superheroes, their kids must learn to work together to save their parents - and the planet.",
//       id: 615677,
//       title: 'We Can Be Heroes',
//       release_date: '2020-12-25',
//       popularity: 2473.191,
//       media_type: 'movie',
//     },
//     {
//       video: false,
//       vote_average: 6.8,
//       overview:
//         "A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.",
//       release_date: '2020-09-03',
//       adult: false,
//       backdrop_path: '/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg',
//       vote_count: 383,
//       genre_ids: [28, 53, 80, 18],
//       id: 553604,
//       original_language: 'en',
//       original_title: 'Honest Thief',
//       poster_path: '/zeD4PabP6099gpE0STWJrJrCBCs.jpg',
//       title: 'Honest Thief',
//       popularity: 2088.646,
//       media_type: 'movie',
//     },
//     {
//       genre_ids: [28, 53],
//       original_language: 'en',
//       original_title: 'Greenland',
//       poster_path: '/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg',
//       title: 'Greenland',
//       id: 524047,
//       overview:
//         "John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
//       release_date: '2020-07-29',
//       vote_count: 1232,
//       vote_average: 7.1,
//       adult: false,
//       backdrop_path: '/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg',
//       video: false,
//       popularity: 1139.453,
//       media_type: 'movie',
//     },
//     {
//       adult: false,
//       id: 11,
//       genre_ids: [12, 28, 878],
//       vote_count: 14858,
//       original_language: 'en',
//       original_title: 'Star Wars',
//       poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
//       title: 'Star Wars',
//       video: false,
//       vote_average: 8.2,
//       backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg',
//       overview:
//         'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',
//       release_date: '1977-05-25',
//       popularity: 126.538,
//       media_type: 'movie',
//     },
//     {
//       overview:
//         'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.',
//       release_date: '2001-12-18',
//       id: 120,
//       adult: false,
//       backdrop_path: '/vRQnzOn4HjIMX4LBq9nHhFXbsSu.jpg',
//       genre_ids: [12, 14, 28],
//       vote_count: 18341,
//       original_language: 'en',
//       original_title: 'The Lord of the Rings: The Fellowship of the Ring',
//       poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
//       video: false,
//       title: 'The Lord of the Rings: The Fellowship of the Ring',
//       vote_average: 8.3,
//       popularity: 74.019,
//       media_type: 'movie',
//     },
//     {
//       vote_average: 6.8,
//       id: 531219,
//       overview:
//         "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
//       release_date: '2020-10-26',
//       adult: false,
//       backdrop_path: '/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg',
//       genre_ids: [14, 10751, 12, 35, 27],
//       vote_count: 1067,
//       original_language: 'en',
//       original_title: "Roald Dahl's The Witches",
//       poster_path: '/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg',
//       title: "Roald Dahl's The Witches",
//       video: false,
//       popularity: 384.437,
//       media_type: 'movie',
//     },
//     {
//       vote_average: 8.3,
//       id: 299534,
//       overview:
//         "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
//       release_date: '2019-04-24',
//       adult: false,
//       backdrop_path: '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
//       genre_ids: [12, 878, 28],
//       vote_count: 16191,
//       original_language: 'en',
//       original_title: 'Avengers: Endgame',
//       poster_path: '/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
//       title: 'Avengers: Endgame',
//       video: false,
//       popularity: 160.449,
//       media_type: 'movie',
//     },
//     {
//       overview:
//         'Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.',
//       release_date: '2020-08-26',
//       adult: false,
//       backdrop_path: '/2AFZyra0Ddwl2oBDhClvD1qSIL6.jpg',
//       id: 340102,
//       genre_ids: [28, 27, 878],
//       vote_count: 1275,
//       original_language: 'en',
//       original_title: 'The New Mutants',
//       poster_path: '/xrI4EnZWftpo1B7tTvlMUXVOikd.jpg',
//       video: false,
//       title: 'The New Mutants',
//       vote_average: 6.4,
//       popularity: 352.645,
//       media_type: 'movie',
//     },
//     {
//       adult: false,
//       backdrop_path: '/zxHHmvUYlYhBuBmZpIrjnamCO3c.jpg',
//       genre_ids: [35, 28],
//       id: 505746,
//       original_language: 'no',
//       original_title: 'Børning 3',
//       overview:
//         'The third and final instalment in the Burnout trilogy. This time, the road leads trough Norway, to Sweden, Denmark and finally Germany to race on the famous racing track, Nürburgring.',
//       poster_path: '/f4xfU5BUrdDeOgt3J6drQGNjfZk.jpg',
//       release_date: '2020-10-14',
//       title: 'Asphalt Burning',
//       video: false,
//       vote_average: 5.9,
//       vote_count: 13,
//       popularity: 97.707,
//       media_type: 'movie',
//     },
//     {
//       overview:
//         "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths -- and about the villain who's to blame.",
//       release_date: '2001-11-16',
//       adult: false,
//       backdrop_path: '/hziiv14OpD73u9gAak4XDDfBKa2.jpg',
//       id: 671,
//       genre_ids: [12, 14],
//       vote_count: 19190,
//       original_language: 'en',
//       original_title: "Harry Potter and the Philosopher's Stone",
//       poster_path: '/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
//       video: false,
//       title: "Harry Potter and the Philosopher's Stone",
//       vote_average: 7.9,
//       popularity: 184.613,
//       media_type: 'movie',
//     },
//     {
//       overview:
//         'A young woman haunted by a tragedy in her past takes revenge on the predatory men unlucky enough to cross her path.',
//       id: 582014,
//       adult: false,
//       backdrop_path: '/7bjFGAK9aEiMQ9nUhanoNDsnV8h.jpg',
//       genre_ids: [53, 80, 18],
//       vote_count: 32,
//       original_language: 'en',
//       original_title: 'Promising Young Woman',
//       poster_path: '/cjzU4g6SlScnP4MdkleyI25KGlR.jpg',
//       title: 'Promising Young Woman',
//       video: false,
//       vote_average: 7.3,
//       release_date: '2020-12-13',
//       popularity: 77.671,
//       media_type: 'movie',
//     },
//     {
//       vote_average: 7.1,
//       id: 337401,
//       overview:
//         'When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.',
//       release_date: '2020-09-04',
//       adult: false,
//       backdrop_path: '/qAKvUu2FSaDlnqznY4VOp5PmjIF.jpg',
//       genre_ids: [12, 14],
//       vote_count: 3865,
//       original_language: 'en',
//       original_title: 'Mulan',
//       poster_path: '/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg',
//       title: 'Mulan',
//       video: false,
//       popularity: 402.145,
//       media_type: 'movie',
//     },
//     {
//       adult: false,
//       backdrop_path: '/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg',
//       genre_ids: [878, 28],
//       id: 560144,
//       original_language: 'en',
//       original_title: 'Skylines',
//       overview:
//         "When a virus threatens to turn the now earth-dwelling friendly alien hybrids against humans, Captain Rose Corley must lead a team of elite mercenaries on a mission to the alien world in order to save what's left of humanity.",
//       poster_path: '/2W4ZvACURDyhiNnSIaFPHfNbny3.jpg',
//       release_date: '2020-12-18',
//       title: 'Skylines',
//       video: false,
//       vote_average: 6.7,
//       vote_count: 28,
//       popularity: 54.156,
//       media_type: 'movie',
//     },
//     {
//       vote_average: 6.8,
//       id: 773655,
//       overview:
//         "2020: A year so [insert adjective of choice here], even the creators of Black Mirror couldn't make it up… but that doesn't mean they don't have a little something to add. This comedy event that tells the story of the dreadful year that was — and perhaps still is? The documentary-style special weaves together some of the world's most (fictitious) renowned voices with real-life archival footage.",
//       release_date: '2020-12-27',
//       adult: false,
//       backdrop_path: '/xxEec408VQY7TIvtpxdkUM3Fux6.jpg',
//       genre_ids: [35],
//       vote_count: 199,
//       original_language: 'en',
//       original_title: 'Death to 2020',
//       poster_path: '/cXYmzvnBNhGPrkH3CWr58sHeZKh.jpg',
//       title: 'Death to 2020',
//       video: false,
//       popularity: 910.183,
//       media_type: 'movie',
//     },
//   ],
//   total_pages: 1000,
//   total_results: 20000,
// };
